http://plantuml.com/salt.html

@startuml
salt
{
  Just plain text
  [This is my button]
  ()  Unchecked radio
  (X) Checked radio
  []  Unchecked box
  [X] Checked box
  "Enter text here   "
  ^This is a droplist^
  ==
  {+
      Login    | "MyName   "
      Password | "****     "
      [Cancel] | [  OK   ]
  }
   Text1
    ..
    "Some field"
    ==
    Note on usage
    ~~
    Another text
    --
    [Ok]
}
@enduml

sfdsdf

@startuml
salt
{
  Just plainasdfasdf text
  [This is my button]
  ()  Unchecked radio
  (X) Checked radio
  []  Unchecked box
  [X] Checked box
  "Enter text here   "
  ^This is a droplist^
  ==
  {+
      Login    | "MyName   "
      Password | "****     "
      [Cancel] | [  OK   ]
  }
   Text1
    ..
    "Some field"
    ==
    Note on usage
    ~~
    Another text
    --
    [Ok]
}
@enduml
